
inherit_from: .rubocop.thoughtbot.yml

AllCops:
  Exclude:
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/**/*'

